-- MySQL Script generated by MySQL Workbench
-- Sat May 16 20:09:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema review_artigos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `review_artigos` ;

-- -----------------------------------------------------
-- Schema review_artigos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `review_artigos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema review_artigos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `review_artigos` ;

-- -----------------------------------------------------
-- Schema review_artigos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `review_artigos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `review_artigos` ;

-- -----------------------------------------------------
-- Table `review_artigos`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `review_artigos`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `review_artigos`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `area_atuacao` VARCHAR(100) NOT NULL,
  `foto_perfil` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `review_artigos`.`artigos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `review_artigos`.`artigos` ;

CREATE TABLE IF NOT EXISTS `review_artigos`.`artigos` (
  `id_artigo` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(150) NOT NULL,
  `resumo` VARCHAR(45) NOT NULL,
  `arquivo_artigo` VARCHAR(200) NULL DEFAULT NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`id_artigo`),
  UNIQUE INDEX `id_artigo_UNIQUE` (`id_artigo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = ascii;


-- -----------------------------------------------------
-- Table `review_artigos`.`notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `review_artigos`.`notas` ;

CREATE TABLE IF NOT EXISTS `review_artigos`.`notas` (
  `fk_usuario` INT NOT NULL,
  `fk_artigo` INT NOT NULL,
  `nota` DECIMAL(4,2) NULL,
  PRIMARY KEY (`fk_usuario`, `fk_artigo`),
  INDEX `fk_curtidas_usuarios_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_nota_artigos1_idx` (`fk_artigo` ASC) VISIBLE,
  CONSTRAINT `fk_curtidas_usuarios`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `review_artigos`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_artigos1`
    FOREIGN KEY (`fk_artigo`)
    REFERENCES `review_artigos`.`artigos` (`id_artigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `review_artigos`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `review_artigos`.`categorias` ;

CREATE TABLE IF NOT EXISTS `review_artigos`.`categorias` (
  `id_categoria` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `review_artigos`.`artigo_categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `review_artigos`.`artigo_categorias` ;

CREATE TABLE IF NOT EXISTS `review_artigos`.`artigo_categorias` (
  `fk_artigo` INT NOT NULL,
  `fk_categoria` INT NOT NULL,
  PRIMARY KEY (`fk_artigo`, `fk_categoria`),
  INDEX `fk_categorias_has_artigos_artigos1_idx` (`fk_artigo` ASC) VISIBLE,
  INDEX `fk_categorias_has_artigos_categorias1_idx` (`fk_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_has_artigos_categorias1`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `review_artigos`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorias_has_artigos_artigos1`
    FOREIGN KEY (`fk_artigo`)
    REFERENCES `review_artigos`.`artigos` (`id_artigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `review_artigos` ;

-- -----------------------------------------------------
-- Table `review_artigos`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `review_artigos`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `review_artigos`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `texto_comentario` VARCHAR(500) NOT NULL,
  `fk_usuario` INT NOT NULL,
  `fk_artigo` INT NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`id_comentario`, `fk_usuario`, `fk_artigo`),
  INDEX `fk_comentarios_usuarios1_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_comentarios_artigos1_idx` (`fk_artigo` ASC) VISIBLE,
  UNIQUE INDEX `id_comentario_UNIQUE` (`id_comentario` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `review_artigos`.`usuarios` (`id_usuario`),
  CONSTRAINT `fk_comentarios_artigos1`
    FOREIGN KEY (`fk_artigo`)
    REFERENCES `review_artigos`.`artigos` (`id_artigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `review_artigos`.`artigos_autores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `review_artigos`.`artigos_autores` ;

CREATE TABLE IF NOT EXISTS `review_artigos`.`artigos_autores` (
  `id_art_autor` INT NOT NULL AUTO_INCREMENT,
  `fk_artigo` INT NOT NULL,
  `fk_usuario` INT NOT NULL,
  `is_usuario` TINYINT NULL,
  `link` VARCHAR(45) NULL,
  PRIMARY KEY (`id_art_autor`, `fk_artigo`, `fk_usuario`),
  INDEX `fk_artigos_has_usuarios_usuarios1_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_artigos_has_usuarios_artigos1_idx` (`fk_artigo` ASC) VISIBLE,
  UNIQUE INDEX `id_art_autor_UNIQUE` (`id_art_autor` ASC) VISIBLE,
  CONSTRAINT `fk_artigos_has_usuarios_artigos1`
    FOREIGN KEY (`fk_artigo`)
    REFERENCES `review_artigos`.`artigos` (`id_artigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artigos_has_usuarios_usuarios1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `review_artigos`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
